[tool.poetry]
name = "speckle"
version = "0.1.0"
description = ""
authors = [
    "Izzy Lyseggen <izzy.lyseggen@gmail.com>",
    "Matteo Cominetti <matteo@speckle.systems>",
    "Gergő Jedlicska <gergo@jedlicska.com>"
]
license = "SEE LICENSE IN readme.md"

[tool.poetry.dependencies]
python = "^3.6.5"
pydantic = "^1.7.3"
gql = "^3.0.0a5"
aiohttp = "^3.7.3"
appdirs = "^1.4.4"
requests = "^2.25.1"
websockets = "^8.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
pytest = "^6.2.2"
pytest-ordering = "^0.6"
pytest-cov = "^2.11.1"
coverage = {extras = ["toml"], version = "^5.4"}
pytest-sugar = "^0.9.4"


[tool.coverage.run]
branch = true
parallel = true
source = ["speckle"]

[tool.coverage.paths]
source = ["speckle"]

[tool.coverage.report]
show_missing = true


[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ["py36", "py37", "py38"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
